name: Cronograma Instagram Financiero
on:
  schedule:
    # Las horas están en UTC (Hora Argentina + 3)
    - cron: '0 13 * * *'  # 10:00 AM Arg (Apertura)
    - cron: '0 16 * * *'  # 01:00 PM Arg (Intermedio)
    - cron: '0 19 * * *'  # 04:00 PM Arg (Cierre Dólar)
    - cron: '0 20 * * *'  # 05:00 PM Arg (Riesgo País)
  workflow_dispatch:      # Para que puedas probarlo vos cuando quieras

jobs:
  ejecutar_bot:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar codigo
        uses: actions/checkout@v3
      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Instalar librerias
        run: pip install requests
      - name: Correr Bot
        run: python bot_dolar.py
