name: Ejecutar Bot Diario
on:
  schedule:
    - cron: '0 13 * * *' # Esto corre todos los días a las 10:00 AM Argentina
  workflow_dispatch: # Esto te permite darle a un botón y probarlo ahora

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar codigo
        uses: actions/checkout@v2
      - name: Configurar Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Instalar librerias
        run: pip install requests
      - name: Ejecutar script
        run: python bot_dolar.py
